Repository YAPP-Github/21st-Web-Team-2-BE, pull requests merged in 2022-12, with the labels that each got.

#5 :memo: Spring Rest Docs 설정
  .gitignore
  build.gradle.kts
  src/docs/asciidoc/actuator-health.adoc
  src/docs/asciidoc/api-docs.adoc
  src/test/kotlin/com/yapp/web2/controller/ApiControllerTest.kt
  src/test/kotlin/com/yapp/web2/controller/actuator/ActuatorControllerTest.kt
Labels: ⚙️ 설정, 📝 문서

#6 🔧 jacoco, codecov 적용
  .github/workflows/codecov-test.yml
  build.gradle.kts
  codecov.yml
Labels: ⚙️ 설정, 📝 문서

#10 ✨ 응답 코드 작성
  build.gradle.kts
  src/main/kotlin/com/yapp/web2/common/anotiation/Generated.kt
  src/main/kotlin/com/yapp/web2/web/api/error/BusinessException.kt
  src/main/kotlin/com/yapp/web2/web/api/error/ErrorCode.kt
  src/main/kotlin/com/yapp/web2/web/api/error/ExceptionHandler.kt
  src/main/kotlin/com/yapp/web2/web/api/response/ApiResponse.kt
  src/main/kotlin/com/yapp/web2/web/api/response/OffsetIdSupport.kt
Labels: ✨ 기능

#12 Soft delete 적용
  src/main/kotlin/com/yapp/web2/common/entity/BaseEntity.kt
  src/main/kotlin/com/yapp/web2/domain/comment/respository/CommentRepository.kt
  src/main/kotlin/com/yapp/web2/domain/comment/respository/ReplyCommentRepository.kt
  src/main/kotlin/com/yapp/web2/domain/like/repository/CommentLikesRepository.kt
  src/main/kotlin/com/yapp/web2/domain/like/repository/VoteLikesRepository.kt
  src/main/kotlin/com/yapp/web2/domain/member/model/Member.kt
  src/main/kotlin/com/yapp/web2/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/yapp/web2/domain/vote/model/Vote.kt
  src/main/kotlin/com/yapp/web2/domain/vote/repository/HashTagRepository.kt
  src/main/kotlin/com/yapp/web2/domain/vote/repository/VoteRepository.kt
  src/main/kotlin/com/yapp/web2/domain/vote/repository/option/VoteOptionMemberRepository.kt
  src/main/kotlin/com/yapp/web2/domain/vote/repository/option/VoteOptionRepository.kt
  src/test/kotlin/com/yapp/web2/domain/vote/model/VoteTest.kt
Labels: ✨ 기능

#14 🔧 Querydsl 설정
  build.gradle.kts
  src/main/kotlin/com/yapp/web2/common/anotiation/Generated.kt
  src/main/kotlin/com/yapp/web2/common/config/QuerydslConfig.kt
  src/main/kotlin/com/yapp/web2/domain/comment/model/Comment.kt
  src/main/kotlin/com/yapp/web2/domain/comment/model/ReplyComment.kt
  src/main/kotlin/com/yapp/web2/domain/like/model/CommentLikes.kt
  src/main/kotlin/com/yapp/web2/domain/like/model/VoteLikes.kt
  src/main/kotlin/com/yapp/web2/domain/member/model/Member.kt
  src/main/kotlin/com/yapp/web2/domain/vote/model/HashTag.kt
  src/main/kotlin/com/yapp/web2/domain/vote/model/Vote.kt
Labels: ⚙️ 설정
