Repository YAPP-Github/21st-Web-Team-2-BE, pull requests merged in 2023-01, with the labels that each got.

#22 ♻️ Api 스펙 네이밍 수정
  src/main/kotlin/com/yapp/web2/web/dto/comment/response/CommentDetailResponse.kt
  src/main/kotlin/com/yapp/web2/web/dto/vote/response/VoteDetailResponse.kt
  src/main/kotlin/com/yapp/web2/web/dto/vote/response/VotePreviewResponse.kt
  src/test/kotlin/com/yapp/web2/domain/vote/application/VoteServiceTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/comment/CommentControllerTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/vote/VoteControllerTest.kt
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/response-fields.snippet
Labels: 📝 문서, ♻️ 리팩토링

#31 ✨ signin, signup 기능
  build.gradle.kts
  src/main/kotlin/com/yapp/web2/common/config/RestTemplateConfig.kt
  src/main/kotlin/com/yapp/web2/common/config/SecurityConfig.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/application/AuthService.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/application/JwtService.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/application/oauth/GoogleOAuthServiceImpl.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/application/oauth/GoogleOAuthToken.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/application/oauth/OAuthService.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/interceptor/JwtInterceptor.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/user/UserDetailsImpl.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/user/UserDetailsServiceImpl.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/util/JwtProvider.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/util/JwtUtil.kt
  src/main/kotlin/com/yapp/web2/domain/member/application/MemberService.kt
  src/main/kotlin/com/yapp/web2/domain/member/model/Member.kt
  src/main/kotlin/com/yapp/web2/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/yapp/web2/web/api/controller/auth/AuthController.kt
  src/main/kotlin/com/yapp/web2/web/api/error/ErrorCode.kt
  src/main/kotlin/com/yapp/web2/web/dto/auth/request/SignUpRequest.kt
  src/main/kotlin/com/yapp/web2/web/dto/auth/response/SignInResponse.kt
  src/main/kotlin/com/yapp/web2/web/dto/jwt/response/JwtTokens.kt
  src/main/kotlin/com/yapp/web2/web/dto/member/response/MemberResponse.kt
  src/main/resources/application-prod.yml
  src/test/kotlin/com/yapp/web2/common/EntityFactory.kt
  src/test/kotlin/com/yapp/web2/domain/comment/application/CommentServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/comment/respository/CommentQuerydslRepositoryTest.kt
  src/test/kotlin/com/yapp/web2/domain/jwt/application/AuthServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/jwt/application/JwtServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/vote/application/VoteServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/vote/model/VoteTest.kt
  src/test/kotlin/com/yapp/web2/domain/vote/repository/VoteQuerydslRepositoryTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/auth/AuthControllerTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/comment/CommentControllerTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/vote/VoteControllerTest.kt
  src/test/resources/application.yml
Labels: ✨ 기능

#33 ✨ 메인 페이지 카테고리로 게시글 필터 API
  src/docs/asciidoc/api-docs.adoc
  src/docs/asciidoc/get-latest-topic-offset.adoc
  src/main/kotlin/com/yapp/web2/domain/member/model/JobCategory.kt
  src/main/kotlin/com/yapp/web2/domain/topic/application/TopicService.kt
  src/main/kotlin/com/yapp/web2/domain/topic/model/Topic.kt
  src/main/kotlin/com/yapp/web2/domain/topic/model/TopicCategory.kt
  src/main/kotlin/com/yapp/web2/domain/topic/repository/TopicQuerydslRepository.kt
  src/main/kotlin/com/yapp/web2/web/api/controller/topic/TopicController.kt
  src/main/kotlin/com/yapp/web2/web/dto/comment/response/CommentDetailResponse.kt
  src/test/kotlin/com/yapp/web2/domain/comment/application/CommentServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/comment/respository/CommentQuerydslRepositoryTest.kt
  src/test/kotlin/com/yapp/web2/domain/topic/application/TopicServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/topic/model/TopicTest.kt
  src/test/kotlin/com/yapp/web2/domain/topic/repository/TopicQuerydslRepositoryTest.kt
  src/test/kotlin/com/yapp/web2/domain/vote/repository/VoteQuerydslRepositoryTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/CommonDocumentationTests.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/comment/CommentControllerTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/topic/TopicControllerTest.kt
Labels: ✨ 기능

#39 ✨ 온보딩시 닉네임 중복 확인 기능
  src/main/kotlin/com/yapp/web2/common/config/SecurityConfig.kt
  src/main/kotlin/com/yapp/web2/domain/member/application/MemberService.kt
  src/main/kotlin/com/yapp/web2/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/yapp/web2/web/api/controller/member/MemberController.kt
  src/main/kotlin/com/yapp/web2/web/api/error/ErrorCode.kt
  src/main/kotlin/com/yapp/web2/web/dto/member/request/NicknameDuplicationRequest.kt
  src/main/kotlin/com/yapp/web2/web/dto/member/response/NicknameDuplicationResponse.kt
  src/test/kotlin/com/yapp/web2/domain/member/application/MemberServiceTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/auth/AuthControllerTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/member/MemberControllerTest.kt
Labels: ✨ 기능

#42 ✨ Topic 생성 Api
  build.gradle.kts
  src/docs/asciidoc/api-docs.adoc
  src/docs/asciidoc/post-topic.adoc
  src/main/kotlin/com/yapp/web2/common/util/CrudRepositoryUtils.kt
  src/main/kotlin/com/yapp/web2/domain/jwt/application/JwtService.kt
  src/main/kotlin/com/yapp/web2/domain/topic/application/TopicService.kt
  src/main/kotlin/com/yapp/web2/domain/topic/model/VoteType.kt
  src/main/kotlin/com/yapp/web2/web/api/controller/topic/TopicController.kt
  src/main/kotlin/com/yapp/web2/web/api/error/ErrorCode.kt
  src/main/kotlin/com/yapp/web2/web/dto/topic/request/TopicPostRequest.kt
  src/main/kotlin/com/yapp/web2/web/dto/topic/response/TopicPostResponse.kt
  src/main/kotlin/com/yapp/web2/web/dto/voteoption/request/VoteOptionPostRequest.kt
  src/test/kotlin/com/yapp/web2/domain/jwt/application/JwtServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/topic/application/TopicServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/topic/model/VoteTypeTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/topic/TopicControllerTest.kt
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
Labels: ⚙️ 설정, 📝 문서, ✨ 기능

#46 ♻️ Api 스펙 네이밍 수정
  src/main/kotlin/com/yapp/web2/domain/member/model/Member.kt
  src/main/kotlin/com/yapp/web2/domain/topic/application/TopicService.kt
  src/main/kotlin/com/yapp/web2/domain/topic/model/VoteType.kt
  src/main/kotlin/com/yapp/web2/domain/topic/model/option/VoteOption.kt
  src/main/kotlin/com/yapp/web2/web/api/controller/comment/CommentController.kt
  src/main/kotlin/com/yapp/web2/web/dto/comment/response/CommentDetailResponse.kt
  src/main/kotlin/com/yapp/web2/web/dto/member/response/MemberResponse.kt
  src/main/kotlin/com/yapp/web2/web/dto/topic/response/TopicDetailResponse.kt
  src/main/kotlin/com/yapp/web2/web/dto/topic/response/TopicPreviewResponse.kt
  src/main/kotlin/com/yapp/web2/web/dto/voteoption/request/VoteOptionPostRequest.kt
  src/main/kotlin/com/yapp/web2/web/dto/voteoption/response/VoteOptionPreviewResponse.kt
  src/test/kotlin/com/yapp/web2/domain/topic/application/TopicServiceTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/comment/CommentControllerTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/topic/TopicControllerTest.kt
Labels: ♻️ 리팩토링

#50 ✨ 투표 API
  src/docs/asciidoc/api-docs.adoc
  src/docs/asciidoc/post-vote.adoc
  src/main/kotlin/com/yapp/web2/common/config/SecurityConfig.kt
  src/main/kotlin/com/yapp/web2/domain/topic/application/option/VoteOptionService.kt
  src/main/kotlin/com/yapp/web2/domain/topic/repository/option/VoteOptionMemberQuerydslRepository.kt
  src/main/kotlin/com/yapp/web2/web/api/controller/voteoption/VoteOptionController.kt
  src/main/kotlin/com/yapp/web2/web/dto/voteoption/request/VotePostRequest.kt
  src/test/kotlin/com/yapp/web2/common/EntityFactory.kt
  src/test/kotlin/com/yapp/web2/domain/topic/application/option/VoteOptionServiceTest.kt
  src/test/kotlin/com/yapp/web2/domain/topic/repository/option/VoteOptionMemberQuerydslRepositoryTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/topic/TopicControllerTest.kt
  src/test/kotlin/com/yapp/web2/web/api/controller/voteoption/VoteOptionControllerTest.kt
Labels: ✨ 기능
